#!/bin/bash

# Remove listing of remote branches, since there are so many
alias gst='(git fetch --all --prune 2>/dev/null && git lol --all --color=always -10 && echo "---" && git lol --color=always -10 && git branch -vv --color=always ; git -c color.status=always status -s) | less -FRX'
alias jst='(                                       git lol --all --color=always -10 && echo "---" && git lol --color=always -10 && git branch -vv --color=always ; git -c color.status=always status -s) | less -FRX'

if [[ "$(uname -a)" == *"Msys"* ]]; then
    alias nv='cd /c/Users/JohanEriksson/NV/SW/BMS'
    __append_dir_to_path_smart "/c/Users/JohanEriksson/AppData/Local/Programs/Microsoft VS Code/bin"
elif [[ "$(uname -a)" == *"WSL2"* ]]; then
    alias nv='cd /mnt/c/Users/JohanEriksson/NV/SW/BMS'
    # TODO : Remove windows centric stuff here
    # /mnt/c/msys64/mingw64/bin
    # /mnt/c/msys64/usr/bin
    # /mnt/c/Users/*/AppData/Local/Microsoft/WindowsApps
    # /mnt/c/Users/*/AppData/Local/Programs/Git/cmd
    # /mnt/c/Users/*/AppData/Local/Programs/Python/Launcher/
    # /mnt/c/Users/*/AppData/Local/Programs/Python/Python310/
    # /mnt/c/Users/*/AppData/Local/Programs/Python/Python310/Scripts/
    # /mnt/c/WINDOWS/System32/OpenSSH/
fi
