#!/bin/bash

git-internal() {
    file="${HOME}/.git-internal"
    if [[ ! -r "${file}" ]]; then
        echo "ERROR: No ${file} found"
        return
    fi
    source "${file}"
    git config --local user.name "${git_internal_name}"
    git config --local user.email "${git_internal_email}"
    git config --local credential.helper 'store --file ${HOME}/.git-internal-credentials'
    git config --show-scope --get-regexp user
    git config --show-scope --get-regexp credential.helper
}

git-external() {
    git config --local --unset user.name
    git config --local --unset user.email
    git config --local --unset credential.helper
    git config --show-scope --get-regexp user
    git config --show-scope --get-regexp credential.helper
}
