#!/usr/bin/env bash
# -*- coding: utf-8 -*-

__git_topic() {
    remote_tracking_branch="$(git rev-parse --abbrev-ref "@{upstream}")"
    upstream="$(git rev-parse --abbrev-ref "@{upstream}" | awk -F'[/]' '{print $1}')"
    remote_default_branch="$(git symbolic-ref "refs/remotes/${upstream}/HEAD" 2>/dev/null | sed 's,^refs/remotes/,,g')"
    current_branch="$(git rev-parse --abbrev-ref HEAD)"
    git lol --not "${remote_default_branch}" --not "${current_branch}" "${remote_tracking_branch}" "$@"
}
