#!/bin/sh

log="/home/monkey/lock.tmp"
echo "$@" > "${log}"
echo >> "${log}"
env >> "${log}"

o_lock="lock"
o_exit="exit"
o_suspend="suspend"
o_reboot="reboot"
o_shutdown="shutdown"

options="${o_lock}
${o_exit}
${o_suspend}
${o_reboot}
${o_shutdown}"

if [[ -z "$1" ]] ; then
    res="$(echo -e "${options}" | dmenu -i -p "system")"
else
    res="$1"
fi

lock() {
    if [[ -z "$(pgrep i3lock)" ]] ; then
        physlock -l
        xset +dpms dpms 2 2 2
        i3lock --color=111111 --nofork
        xset -dpms
        physlock -L
    fi
}

case "${res}" in
    "${o_lock}")
        lock
        ;;
    "${o_exit}")
        i3-msg exit
        ;;
    "${o_suspend}")
        systemctl suspend
        ;;
    "${o_reboot}")
        systemctl reboot
        ;;
    "${o_shutdown}")
        systemctl poweroff
        ;;
    *)
        exit 1
        ;;
esac
