#!/bin/bash

o_reset="reset"
o_duplicate="duplicate"
o_extend="extend"
o_external="external"
o_hd="hd"
o_zoom="zoom"

options="${o_reset}
${o_duplicate}
${o_extend}
${o_external}
${o_hd}
${o_zoom}"

if [[ -z "$1" ]] ; then
    res="$(echo -e "${options}" | dmenu -i -p "monitor")"
else
    res="$1"
fi

case "${res}" in
    "${o_reset}")
        xrandr --output HDMI1 --off
        xrandr --output eDP1 --auto --scale 1x1
        ;;
    "${o_duplicate}")
        xrandr --output eDP1 --auto --scale 1x1
        xrandr --output HDMI1 --auto --same-as eDP1
        ;;
    "${o_extend}")
        # Set zoom level
        xrandr --output eDP1 --auto --scale 0.8x.8
        xrandr --output HDMI1 --auto --right-of eDP1
        ;;
    "${o_external}")
        xrandr --output eDP1 --off
        xrandr --output HDMI1 --auto
        ;;
    "${o_hd}")
        xrandr --output eDP1 --off
        xrandr --output HDMI1 --mode 1280x720
        ;;
    "${o_zoom}")
        xrandr --output HDMI1 --off
        xrandr --output eDP1 --auto --scale 0.8x.8
        ;;
    *)
        exit 1
        ;;
esac

# Fix wallpaper
feh --bg-scale $HOME/pic/wallpaper
