#!/usr/bin/env bash
# -*- coding: utf-8 -*-

dbus-monitor --session "type='signal',interface='org.freedesktop.ScreenSaver',path='/org/freedesktop/ScreenSaver',member='ActiveChanged'" | \
( while true; do
    read X
    if echo "${X}" | grep "boolean true" &> /dev/null ; then
        echo "Screen locked on $(date --rfc-3339=seconds)"
    fi
    if echo "${X}" | grep "boolean false" &> /dev/null ; then
        echo "Screen unlocked on $(date --rfc-3339=seconds)"
    fi
done )
