[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "clang-format", args = ["--style=file"] }
auto-format = true

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "clang-format", args = ["--style=file"] }
auto-format = true

[[language]]
name = "cmake"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "toml"
language-servers = ["tombi"]
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "prettier", args = [
  "--parser=markdown",
  "--prose-wrap=always"
] }
auto-format = true
